onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate /tb_main_fsmc/clk
add wave -noupdate /tb_main_fsmc/rst_n
add wave -noupdate -color Yellow -radix unsigned /tb_main_fsmc/fsmc_A
add wave -noupdate -color Yellow -radix unsigned -childformat {{{/tb_main_fsmc/fsmc_D[15]} -radix unsigned} {{/tb_main_fsmc/fsmc_D[14]} -radix unsigned} {{/tb_main_fsmc/fsmc_D[13]} -radix unsigned} {{/tb_main_fsmc/fsmc_D[12]} -radix unsigned} {{/tb_main_fsmc/fsmc_D[11]} -radix unsigned} {{/tb_main_fsmc/fsmc_D[10]} -radix unsigned} {{/tb_main_fsmc/fsmc_D[9]} -radix unsigned} {{/tb_main_fsmc/fsmc_D[8]} -radix unsigned} {{/tb_main_fsmc/fsmc_D[7]} -radix unsigned} {{/tb_main_fsmc/fsmc_D[6]} -radix unsigned} {{/tb_main_fsmc/fsmc_D[5]} -radix unsigned} {{/tb_main_fsmc/fsmc_D[4]} -radix unsigned} {{/tb_main_fsmc/fsmc_D[3]} -radix unsigned} {{/tb_main_fsmc/fsmc_D[2]} -radix unsigned} {{/tb_main_fsmc/fsmc_D[1]} -radix unsigned} {{/tb_main_fsmc/fsmc_D[0]} -radix unsigned}} -subitemconfig {{/tb_main_fsmc/fsmc_D[15]} {-color Yellow -height 15 -radix unsigned} {/tb_main_fsmc/fsmc_D[14]} {-color Yellow -height 15 -radix unsigned} {/tb_main_fsmc/fsmc_D[13]} {-color Yellow -height 15 -radix unsigned} {/tb_main_fsmc/fsmc_D[12]} {-color Yellow -height 15 -radix unsigned} {/tb_main_fsmc/fsmc_D[11]} {-color Yellow -height 15 -radix unsigned} {/tb_main_fsmc/fsmc_D[10]} {-color Yellow -height 15 -radix unsigned} {/tb_main_fsmc/fsmc_D[9]} {-color Yellow -height 15 -radix unsigned} {/tb_main_fsmc/fsmc_D[8]} {-color Yellow -height 15 -radix unsigned} {/tb_main_fsmc/fsmc_D[7]} {-color Yellow -height 15 -radix unsigned} {/tb_main_fsmc/fsmc_D[6]} {-color Yellow -height 15 -radix unsigned} {/tb_main_fsmc/fsmc_D[5]} {-color Yellow -height 15 -radix unsigned} {/tb_main_fsmc/fsmc_D[4]} {-color Yellow -height 15 -radix unsigned} {/tb_main_fsmc/fsmc_D[3]} {-color Yellow -height 15 -radix unsigned} {/tb_main_fsmc/fsmc_D[2]} {-color Yellow -height 15 -radix unsigned} {/tb_main_fsmc/fsmc_D[1]} {-color Yellow -height 15 -radix unsigned} {/tb_main_fsmc/fsmc_D[0]} {-color Yellow -height 15 -radix unsigned}} /tb_main_fsmc/fsmc_D
add wave -noupdate -radix unsigned /tb_main_fsmc/fsmc_wdata
add wave -noupdate -radix unsigned /tb_main_fsmc/fsmc_rdata
add wave -noupdate /tb_main_fsmc/fsmc_NE
add wave -noupdate /tb_main_fsmc/fsmc_NWE
add wave -noupdate /tb_main_fsmc/fsmc_NOE
add wave -noupdate -radix unsigned -childformat {{{/tb_main_fsmc/hostRece[15]} -radix unsigned} {{/tb_main_fsmc/hostRece[14]} -radix unsigned} {{/tb_main_fsmc/hostRece[13]} -radix unsigned} {{/tb_main_fsmc/hostRece[12]} -radix unsigned} {{/tb_main_fsmc/hostRece[11]} -radix unsigned} {{/tb_main_fsmc/hostRece[10]} -radix unsigned} {{/tb_main_fsmc/hostRece[9]} -radix unsigned} {{/tb_main_fsmc/hostRece[8]} -radix unsigned} {{/tb_main_fsmc/hostRece[7]} -radix unsigned} {{/tb_main_fsmc/hostRece[6]} -radix unsigned} {{/tb_main_fsmc/hostRece[5]} -radix unsigned} {{/tb_main_fsmc/hostRece[4]} -radix unsigned} {{/tb_main_fsmc/hostRece[3]} -radix unsigned} {{/tb_main_fsmc/hostRece[2]} -radix unsigned} {{/tb_main_fsmc/hostRece[1]} -radix unsigned} {{/tb_main_fsmc/hostRece[0]} -radix unsigned}} -subitemconfig {{/tb_main_fsmc/hostRece[15]} {-radix unsigned} {/tb_main_fsmc/hostRece[14]} {-radix unsigned} {/tb_main_fsmc/hostRece[13]} {-radix unsigned} {/tb_main_fsmc/hostRece[12]} {-radix unsigned} {/tb_main_fsmc/hostRece[11]} {-radix unsigned} {/tb_main_fsmc/hostRece[10]} {-radix unsigned} {/tb_main_fsmc/hostRece[9]} {-radix unsigned} {/tb_main_fsmc/hostRece[8]} {-radix unsigned} {/tb_main_fsmc/hostRece[7]} {-radix unsigned} {/tb_main_fsmc/hostRece[6]} {-radix unsigned} {/tb_main_fsmc/hostRece[5]} {-radix unsigned} {/tb_main_fsmc/hostRece[4]} {-radix unsigned} {/tb_main_fsmc/hostRece[3]} {-radix unsigned} {/tb_main_fsmc/hostRece[2]} {-radix unsigned} {/tb_main_fsmc/hostRece[1]} {-radix unsigned} {/tb_main_fsmc/hostRece[0]} {-radix unsigned}} /tb_main_fsmc/hostRece
add wave -noupdate -radix unsigned -childformat {{{/tb_main_fsmc/data[2]} -radix unsigned} {{/tb_main_fsmc/data[1]} -radix unsigned} {{/tb_main_fsmc/data[0]} -radix unsigned}} -subitemconfig {{/tb_main_fsmc/data[2]} {-height 15 -radix unsigned} {/tb_main_fsmc/data[1]} {-height 15 -radix unsigned} {/tb_main_fsmc/data[0]} {-height 15 -radix unsigned}} /tb_main_fsmc/data
add wave -noupdate -color Yellow -radix unsigned /tb_main_fsmc/u_design_main_fsmc/w_addr
add wave -noupdate -color Yellow -radix unsigned -childformat {{{/tb_main_fsmc/u_design_main_fsmc/w_wdata[15]} -radix unsigned} {{/tb_main_fsmc/u_design_main_fsmc/w_wdata[14]} -radix unsigned} {{/tb_main_fsmc/u_design_main_fsmc/w_wdata[13]} -radix unsigned} {{/tb_main_fsmc/u_design_main_fsmc/w_wdata[12]} -radix unsigned} {{/tb_main_fsmc/u_design_main_fsmc/w_wdata[11]} -radix unsigned} {{/tb_main_fsmc/u_design_main_fsmc/w_wdata[10]} -radix unsigned} {{/tb_main_fsmc/u_design_main_fsmc/w_wdata[9]} -radix unsigned} {{/tb_main_fsmc/u_design_main_fsmc/w_wdata[8]} -radix unsigned} {{/tb_main_fsmc/u_design_main_fsmc/w_wdata[7]} -radix unsigned} {{/tb_main_fsmc/u_design_main_fsmc/w_wdata[6]} -radix unsigned} {{/tb_main_fsmc/u_design_main_fsmc/w_wdata[5]} -radix unsigned} {{/tb_main_fsmc/u_design_main_fsmc/w_wdata[4]} -radix unsigned} {{/tb_main_fsmc/u_design_main_fsmc/w_wdata[3]} -radix unsigned} {{/tb_main_fsmc/u_design_main_fsmc/w_wdata[2]} -radix unsigned} {{/tb_main_fsmc/u_design_main_fsmc/w_wdata[1]} -radix unsigned} {{/tb_main_fsmc/u_design_main_fsmc/w_wdata[0]} -radix unsigned}} -subitemconfig {{/tb_main_fsmc/u_design_main_fsmc/w_wdata[15]} {-color Yellow -radix unsigned} {/tb_main_fsmc/u_design_main_fsmc/w_wdata[14]} {-color Yellow -radix unsigned} {/tb_main_fsmc/u_design_main_fsmc/w_wdata[13]} {-color Yellow -radix unsigned} {/tb_main_fsmc/u_design_main_fsmc/w_wdata[12]} {-color Yellow -radix unsigned} {/tb_main_fsmc/u_design_main_fsmc/w_wdata[11]} {-color Yellow -radix unsigned} {/tb_main_fsmc/u_design_main_fsmc/w_wdata[10]} {-color Yellow -radix unsigned} {/tb_main_fsmc/u_design_main_fsmc/w_wdata[9]} {-color Yellow -radix unsigned} {/tb_main_fsmc/u_design_main_fsmc/w_wdata[8]} {-color Yellow -radix unsigned} {/tb_main_fsmc/u_design_main_fsmc/w_wdata[7]} {-color Yellow -radix unsigned} {/tb_main_fsmc/u_design_main_fsmc/w_wdata[6]} {-color Yellow -radix unsigned} {/tb_main_fsmc/u_design_main_fsmc/w_wdata[5]} {-color Yellow -radix unsigned} {/tb_main_fsmc/u_design_main_fsmc/w_wdata[4]} {-color Yellow -radix unsigned} {/tb_main_fsmc/u_design_main_fsmc/w_wdata[3]} {-color Yellow -radix unsigned} {/tb_main_fsmc/u_design_main_fsmc/w_wdata[2]} {-color Yellow -radix unsigned} {/tb_main_fsmc/u_design_main_fsmc/w_wdata[1]} {-color Yellow -radix unsigned} {/tb_main_fsmc/u_design_main_fsmc/w_wdata[0]} {-color Yellow -radix unsigned}} /tb_main_fsmc/u_design_main_fsmc/w_wdata
add wave -noupdate -color Yellow -radix unsigned -childformat {{{/tb_main_fsmc/u_design_main_fsmc/w_rdata[15]} -radix unsigned} {{/tb_main_fsmc/u_design_main_fsmc/w_rdata[14]} -radix unsigned} {{/tb_main_fsmc/u_design_main_fsmc/w_rdata[13]} -radix unsigned} {{/tb_main_fsmc/u_design_main_fsmc/w_rdata[12]} -radix unsigned} {{/tb_main_fsmc/u_design_main_fsmc/w_rdata[11]} -radix unsigned} {{/tb_main_fsmc/u_design_main_fsmc/w_rdata[10]} -radix unsigned} {{/tb_main_fsmc/u_design_main_fsmc/w_rdata[9]} -radix unsigned} {{/tb_main_fsmc/u_design_main_fsmc/w_rdata[8]} -radix unsigned} {{/tb_main_fsmc/u_design_main_fsmc/w_rdata[7]} -radix unsigned} {{/tb_main_fsmc/u_design_main_fsmc/w_rdata[6]} -radix unsigned} {{/tb_main_fsmc/u_design_main_fsmc/w_rdata[5]} -radix unsigned} {{/tb_main_fsmc/u_design_main_fsmc/w_rdata[4]} -radix unsigned} {{/tb_main_fsmc/u_design_main_fsmc/w_rdata[3]} -radix unsigned} {{/tb_main_fsmc/u_design_main_fsmc/w_rdata[2]} -radix unsigned} {{/tb_main_fsmc/u_design_main_fsmc/w_rdata[1]} -radix unsigned} {{/tb_main_fsmc/u_design_main_fsmc/w_rdata[0]} -radix unsigned}} -subitemconfig {{/tb_main_fsmc/u_design_main_fsmc/w_rdata[15]} {-color Yellow -radix unsigned} {/tb_main_fsmc/u_design_main_fsmc/w_rdata[14]} {-color Yellow -radix unsigned} {/tb_main_fsmc/u_design_main_fsmc/w_rdata[13]} {-color Yellow -radix unsigned} {/tb_main_fsmc/u_design_main_fsmc/w_rdata[12]} {-color Yellow -radix unsigned} {/tb_main_fsmc/u_design_main_fsmc/w_rdata[11]} {-color Yellow -radix unsigned} {/tb_main_fsmc/u_design_main_fsmc/w_rdata[10]} {-color Yellow -radix unsigned} {/tb_main_fsmc/u_design_main_fsmc/w_rdata[9]} {-color Yellow -radix unsigned} {/tb_main_fsmc/u_design_main_fsmc/w_rdata[8]} {-color Yellow -radix unsigned} {/tb_main_fsmc/u_design_main_fsmc/w_rdata[7]} {-color Yellow -radix unsigned} {/tb_main_fsmc/u_design_main_fsmc/w_rdata[6]} {-color Yellow -radix unsigned} {/tb_main_fsmc/u_design_main_fsmc/w_rdata[5]} {-color Yellow -radix unsigned} {/tb_main_fsmc/u_design_main_fsmc/w_rdata[4]} {-color Yellow -radix unsigned} {/tb_main_fsmc/u_design_main_fsmc/w_rdata[3]} {-color Yellow -radix unsigned} {/tb_main_fsmc/u_design_main_fsmc/w_rdata[2]} {-color Yellow -radix unsigned} {/tb_main_fsmc/u_design_main_fsmc/w_rdata[1]} {-color Yellow -radix unsigned} {/tb_main_fsmc/u_design_main_fsmc/w_rdata[0]} {-color Yellow -radix unsigned}} /tb_main_fsmc/u_design_main_fsmc/w_rdata
add wave -noupdate /tb_main_fsmc/u_design_main_fsmc/w_wen
add wave -noupdate /tb_main_fsmc/u_design_main_fsmc/w_ren
add wave -noupdate -color Cyan -radix unsigned /tb_main_fsmc/u_design_main_fsmc/w_sum_i
add wave -noupdate -color Cyan -radix unsigned /tb_main_fsmc/u_design_main_fsmc/w_num1_o
add wave -noupdate -color Cyan -radix unsigned /tb_main_fsmc/u_design_main_fsmc/w_num2_o
add wave -noupdate -color Cyan -radix unsigned /tb_main_fsmc/u_design_main_fsmc/w_num3_o
add wave -noupdate /tb_main_fsmc/u_design_main_fsmc/w_sys_en
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {11700 ns} 0}
quietly wave cursor active 1
configure wave -namecolwidth 150
configure wave -valuecolwidth 100
configure wave -justifyvalue left
configure wave -signalnamewidth 1
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ns
update
WaveRestoreZoom {11261 ns} {12389 ns}
